@startuml Application Class Diagram

Title Application Class Diagram

package "APPTurtle" as app_package {
    class "App" as app {
        - m_ros : MicroRosClient
        + setup() : void
        + loop() : void
    }

    class "MicroRosClient" as ros_wrapper {
        - m_node : rcl_node_t
        - m_executor : rclc_executor_t
        - m_agentConfiguration : micro_ros_agent_locator
        - m_subscribtions : *Subscriber[MAX_SUBSCRIPTIONS]
        - m_nodeName : String
        - m_nodeNamespace : String
        + MicroRosClient()
        + setConfiguration(const String &nodeName, const String &nodeNamespace, const String& agentAddress, uint16_t agentPort) : bool
        + process() : bool
        + createSubscriber(Subscriber*) : bool
    }

    class "BaseSubscriber" as baseSub
    {
        - m_topicName : String
        + getTopicName() : String
    }

    class "Subscriber"<typename messageType> {
        - messageBuffer : messageType
        - m_subscribtion : rcl_subscription_t*
        - m_callback : RosTopicCallback*
        + std::function<void(const void*)> RosTopicCallback;
        + Subscriber(const String &topicName, const rosidl_message_type_support_t *type_support, const std::function<void(const void*)> &callback)
        + setSubscription(rcl_subscription_t*): bool
    }

    app *--> ros_wrapper
    ros_wrapper --|> baseSub : <<use>>
    baseSub <|-- Subscriber : <<inherit>>
}

package "RCLC" as rclc {
    class "rcl_node_t" as rcl_node {
    }

    class "rclc_executor_t" as rclc_executor {
    }

    class "micro_ros_agent_locator" as micro_ros_agent_locator {
    }

    class "rcl_allocator_t" as rcl_allocator {
    }

    class "rclc_support_t" as rclc_support {
    }

    class "rcl_subscription_t" as rcl_subscription {
    }

    ' class "rcl_publisher_t" as rcl_publisher {
    ' }
}

ros_wrapper *--> rcl_node
ros_wrapper *--> rclc_executor
ros_wrapper *--> micro_ros_agent_locator
ros_wrapper --|> rcl_allocator : <<use>>
ros_wrapper --|> rclc_support : <<use>>

Subscriber *--> rcl_subscription
' ros_wrapper --|> rcl_publisher : <<use>>


' note left of rclc
' Default library values:
' MAX_PUBLISHERS = 10
' MAX_SUBSCRIPTIONS = 5
' end note


@enduml