@startuml TurtleSim for DCS

node "PC" {
    package "Webots" {
        component "WebotsSim" <<executable>> as wbsim
        component "World file" <<world>> as world
        component "Zumo"  <<proto>> as wbZumoProto
        component "ZumoComSystem"  <<proto>> as wbDcsProto
        component "ROS2SupervisorProto" <<proto>> as wbRos2Proto

        wbsim ..> world
        wbsim ..> wbZumoProto
        wbsim ..> wbDcsProto
        wbsim ..> wbRos2Proto
    }
    note left of Webots
        Standard Zumo world setup
    end note

    package "ROS2" {
        cloud "ROS2 Logical Network" as ros2LogicalNetwork

        node "teleop_turtle" <<executable>> as teleopTurtle {
            component "/teleop_turtle" <<ros2-node>> as teleopTurtleNode
        }

        node "Ros2SuperVisor" <<executable>> as wbSupervisorApp {
            component "/Ros2SuperVisor/Ros2SuperVisor" <<ros2-node>> as ros2SupervisorNode
            note bottom of ros2SupervisorNode
                Simulation time through /clock topic.
                May not be required.
            end note
        }

        node "DroidControlShip" <<executable>> as dcs {
            package "AppTurtle" <<app>> as turtleApp #YellowGreen {
                component "libController" <<lib>>
                component "MicroRosClient" <<lib>>
            }
            note left of turtleApp
                Translates between ROS2 messaging and
                RemoteControl SerMux protocol.
            end note

            component "/dcs" <<ros2-node>> as dcs_node
            note bottom of dcs_node
                Not used for TurtleSim.
                Only shown as an example for
                cs specific node.
                Could be GPS, LEDs...
            end note

            component "/dcs_zumo" <<ros2-node>> as dcs_zumo_node #YellowGreen
        }
        note left of dcs
            DCS is a ROS2 package
            that acts as a webots controller.
        end note

        node "micro-ROS\nAgent" <<executable>> as agent

        turtleApp .u.> dcs_node
        turtleApp .u.> dcs_zumo_node

        teleopTurtleNode ---> dcs_zumo_node : geometry_msgs/Twist

        agent -u-> ros2LogicalNetwork
        dcs <-> agent : \n\nXRCE protocol over UDP
    }

    package "RadonUlzer" {
        node "RemoteControl" <<executable>> as radonUlzerRc {
            package "RemoteControlApp" <<app>> as AppRadonUlzerRc
        }
    }

    interface Socket
    note left of Socket
        Webots Controller API Messages
        over TCP/IP socket.
    end note

    wbsim -u-() Socket
    turtleApp --( Socket : To ZumoComSystem proto
    radonUlzerRc --( Socket : To Zumo proto

    turtleApp <-> AppRadonUlzerRc : SerMux over simulated serial comm in Webots

    wbRos2Proto ---- ros2SupervisorNode

@enduml
