@startuml

title Target

node "Environment" as env {

    node "Zumo32U4" <<robot>> as robot {

        node "Radon Ulzer" <<firmware>> as ru

        note left of ru
            * Connects as external controller to the simulation.
            * Provides sensor data via SerialMuxProt to the DroidControlShip.
            * Requires actor data via SerialMuxProt from the DroidControlShip, but
                depends on which kind of application is compiled.
        end note
    }

    node "ZumoComSystem" <<shield>> as shield {

        node "Droid Control Ship" <<firmware>> as dcs

        note left of dcs
            * The Droid Control Ship provides the calculation power,
            * and the connectivity to the outer world of the Radon Ulzer.
        end note
    }

    interface "Serial via USB" as iRobotSerial
    interface "Electrical" as iEE

    shield --( iEE
    iEE -- robot
}

node "MQTT Broker" as broker {
}

dcs --( iRobotSerial
iRobotSerial -- ru: <<protocol>>\nSerialMuxProt

interface "TCP/IP" as iNetwork

broker -- iNetwork: <<protocol>>\nMQTT
iNetwork )-- dcs

@enduml
