; PlatformIO Project Configuration File
;
; Used for user specific configurations.

; *****************************************************************************
; Common configurations, which is independed of the environment.
; *****************************************************************************
[common]

; *****************************************************************************
; Target environment for DroidControlShip.
; *****************************************************************************
[target:esp32]

; *****************************************************************************
; PC target environment for Webots simulation.
;
; It is assumed that the environment variable WEBOTS_HOME is set to the
; Webots directory, e.g. WEBOTS_HOME=C:\Users\<user>\AppData\Local\Programs\Webots
; *****************************************************************************
[target:Sim]
custom_webots_protocol = tcp ; [ipc|tcp] - ipc is faster but only works on the same machine, tcp works also over network
custom_webots_ip_address = 172.31.0.1 ; IP address of the Webots simulation (only used for TCP protocol). Under WSL run 'ip route show | grep default' to find out.
custom_webots_robot_name = ZumoComSystem
custom_webots_robot_serial_rx_channel = 4
custom_webots_robot_serial_tx_channel = 3
