@startuml ClassDiagram
package "SerialMuxChannels" <<namespace>> {

  ' ===== Enums =====
  package "SMPChannelPayload" <<namespace>> {
    enum CmdId {
      CMD_ID_IDLE
      CMD_ID_START_LINE_SENSOR_CALIB
      CMD_ID_START_MOTOR_SPEED_CALIB
      CMD_ID_REINIT_BOARD
      CMD_ID_GET_MAX_SPEED
      CMD_ID_START_DRIVING
      CMD_ID_SET_INIT_POS
    }
    enum RspId {
      RSP_ID_OK
      RSP_ID_PENDING
      RSP_ID_ERROR
    }
    enum Status {
      STATUS_FLAG_OK
      STATUS_FLAG_ERROR
    }
    enum Range
  }

  ' ===== Payload-Structs =====
  class Command <<struct>> {
    +commandId : SMPChannelPayload::CmdId
    --
    +xPos : int32_t  ' [mm]   (nur für SET_INIT_POS)
    +yPos : int32_t  ' [mm]
    +orientation : int32_t  ' [mrad]
  }

  class CommandResponse <<struct>> {
    +commandId : SMPChannelPayload::CmdId
    +responseId : SMPChannelPayload::RspId
    --
    +maxMotorSpeed : int32_t  ' [mm/s]
  }

  class MotorSpeed <<struct>> {
    +left  : int32_t  ' [mm/s]
    +right : int32_t  ' [mm/s]
  }

  class RobotSpeed <<struct>> {
    +linearCenter : int32_t  ' [mm/s]
    +angular      : int32_t  ' [mrad/s]
  }

  class VehicleData <<struct>> {
    +xPos        : int32_t  ' [mm]
    +yPos        : int32_t  ' [mm]
    +orientation : int32_t  ' [mrad]
    +left        : int32_t  ' [mm/s]
    +right       : int32_t  ' [mm/s]
    +center      : int32_t  ' [mm/s]
    +proximity   : SMPChannelPayload::Range
  }

  class Status <<struct>> {
    +status : SMPChannelPayload::Status
  }

  class LineSensorData <<struct>> {
    +lineSensorData : uint16_t[5]  ' normiert, max 1000
  }

  note as N_channels
  CHANNELS:
   - "CMD"        (DLC = sizeof(Command))
   - "CMD_RSP"    (DLC = sizeof(CommandResponse))
   - "MOTOR_SET"  (DLC = sizeof(MotorSpeed))
   - "ROBOT_SET"  (DLC = sizeof(RobotSpeed))
   - "CURR_DATA"  (DLC = sizeof(VehicleData))
   - "STATUS"     (DLC = sizeof(Status))
   - "LINE_SENS"  (DLC = sizeof(LineSensorData))
  end note
}

class SerMuxChannelProvider {
  +SerMuxChannelProvider(stream: Stream&)
  +init() : bool
  +isInSync() : bool
  +process() : void
  --
  +registerLineSensorCallback(cb) : void
  +registerVehicleDataCallback(cb) : void
  --
  +sendStatus(status: Status) : bool
  +sendMotorSpeed(motorSpeed: MotorSpeed) : bool
  +sendRobotSpeed(robotSpeed: RobotSpeed) : bool
  --
  +requestMaxMotorSpeed(cb) : bool
  +requestLineSensorCalibration(cb) : bool
  +requestMotorSpeedCalibration(cb) : bool
  +requestReinitBoard(cb) : bool
}
@enduml