@startuml MQTT State Machine

Title MQTT State Machine
hide empty description

state "Uninitialized" as Uninitialized
state "Setup" as Setup
state "Connecting" as Connecting
state "Connected" as Connected
state "Disconnecting" as Disconnecting
state "Disconnected" as Disconnected



[*] --> Uninitialized : Instanciation of\nthe MQTT Client
Uninitialized --> Setup : [Library initialized]
Uninitialized <-- Setup : [Fatal Error on\nClient Creation]
Setup --> Disconnected : [Configuration\nset]
Disconnected --> Connecting : [Connection\ninitiated]
Connecting --> Connected : [Connection\nestablished]
Disconnected <-- Connecting : [Connection\ntimed out]
Disconnected <-- Disconnecting : [Disconected from Broker]
Disconnecting <-- Connected : [Disconnect\nrequest]

note right of Setup
    Configuration:
    - Broker Address
    - Broker Port
    - Client ID
    - Birth Topic
    - Birth Message
    - Will Topic
    - Will Message
    - Reconnect Flag
end note

note as N1
process() calls the mqtt_client loop.
The return value is saved in a member variable
and then read by each state as required.
end note

@enduml