@startuml

title State Diagram LineFollower

state "Driving State" as DrivingState
state "Error State" as ErrorState
state "LineSensorCalibrationState" as LineSensorCalibrationState
state "ReadyState" as ReadyState
state "ReleaseTrackState" as ReleaseTrackState
state "StartupState" as StartupState



[*] --> StartupState
StartupState --> LineSensorCalibrationState : onInitialized
LineSensorCalibrationState --> ReadyState : onCalibrated
LineSensorCalibrationState --> ErrorState : onError
ReadyState --> ReleaseTrackState : onButtonPressed
ReadyState --> ErrorState : onError

ReleaseTrackState --> DrivingState : afterDelay
DrivingState --> ReadyState : afterRunComplete

@enduml