@startuml ZumoSim_MQTT
skinparam dpi 150
skinparam componentStyle rectangle
skinparam ArrowColor #555
skinparam ArrowThickness 1.2
skinparam defaultFontName Helvetica

node "PC" as PC {

  package "Webots" {
    node "Zumo32U4" <<sim>> as wbZumo
    node "ZumoComSystem" <<sim>> as wbDcs
    node "Camera" <<sim>> as wbCamera
  }

  package "Host Apps" {
    node "DroidControlShip" <<executable>> as DCS {
      component "LineFollower" <<app>> as LineFollowerApp
    }
    node "RadonUlzer" <<executable>> as RadonUlzer {
      component "RemoteControl" <<app>> as RemoteControlApp
    }
    node "SpaceShipRadar" <<executable>> as ssr
    node "MQTT Broker" as broker
  }

  interface "Socket" as SocketCamera
  interface "Socket" as SocketDCS
  interface "Socket" as SocketRemoteCTRL

  wbCamera --() SocketCamera: <<protocol>>\nWebots specific
  ssr --( SocketCamera
  wbDcs --() SocketDCS: <<protocol>>\nWebots specific
  DCS --( SocketDCS
  wbZumo --() SocketRemoteCTRL: <<protocol>>\nWebots specific
  RadonUlzer --( SocketRemoteCTRL


  wbZumo <--> wbDcs : virtual serial
  ssr --> broker : MQTT (Publish)
  DCS <--> broker : MQTT (Publish/Subscribe)
}
@enduml
