@startuml ZumoReal_MQTT
skinparam dpi 150
skinparam componentStyle rectangle
skinparam ArrowColor #555
skinparam ArrowThickness 1.2
skinparam defaultFontName Helvetica



node "Robot Hardware" {
node "ZumoComSystem" <<device>> as ZCS {
    component "DroidControlShip" <<executable>> as DCS {
    component "LineFollower" <<app>> as LineFollowerApp
    }
}

node "Pololu Zumo32U4" <<device>> as ZUMO {
    component "RadonUlzer" <<executable>> as RadonUlzer {
    component "RemoteControl" <<app>> as RemoteControlApp
    }
}
}

node "Laptop / PC" <<device>> as HOST {
    component "MQTT Broker" <<executable>> as BROKER
    component "SpaceShipRadar" <<executable>> as SSR
}

component "Camera" <<device>> as CAMERA

ZUMO <--> ZCS : UART / SerialMux
SSR --> BROKER : MQTT (Publish)
CAMERA -- SSR : USB 



@enduml
